// AUTH
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';

// NAV
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_PATHNAME = 'UPDATE_PATHNAME';

// SITE
export const FETCH_SITE = 'FETCH_SITE';
export const CREATE_SITE = 'CREATE_SITE';
export const UPDATE_SITE = 'UPDATE_SITE';
export const DELETE_SITE = 'DELETE_SITE';

// ORDER
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

// CATEGORY
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// PRODUCT
export const UPDATE_CURRENT_PRODUCT = 'UPDATE_CURRENT_PRODUCT';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_ANALYTICS = 'FETCH_PRODUCT_ANALYTICS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
