// AUTH
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';

// NAV
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_PATHNAME = 'UPDATE_PATHNAME';

// CATEGORY
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// PRODUCT
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_ANALYTICS = 'FETCH_PRODUCT_ANALYTICS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_LOCATIONS = 'UPDATE_PRODUCT_LOCATIONS';
export const RESET_PRODUCT_LOCATIONS = 'RESET_PRODUCT_LOCATIONS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
